"""Exports the built benchmark into a HuggingFace-ready dataset layout.

Produces one repo with three **configs** (create / fix / modify), each with
`train` and `test` splits, plus a dataset-card `README.md` carrying the `configs:`
front-matter, licence, attribution, and per-split counts. Upload the output dir with
`huggingface-cli upload <repo> <output_dir> .` (or `datasets.load_dataset(<dir>)`).

JSON-valued fields (`schema`, `reference_json`, etc.) are serialized to strings so
the dataset has a uniform, Arrow-friendly schema across heterogeneous instances —
the same convention JSONSchemaBench uses. Consumers `json.loads` those fields.

Usage:
    uv run python src/export_hf.py --config configs/export_hf.json
"""

import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import argparse
import json
import datetime


def _stringify(record):
    """Serialize dict/list values to strings; leave scalars as-is (uniform schema)."""
    return {k: (json.dumps(v) if isinstance(v, (dict, list)) else v) for k, v in record.items()}


def _write_split(src_dir, out_path):
    """Reads per-instance JSON files from src_dir into one JSONL. Returns count."""
    if not os.path.isdir(src_dir):
        return 0
    n = 0
    with open(out_path, "w", encoding="utf-8") as out:
        for fn in sorted(os.listdir(src_dir)):
            if not fn.endswith(".json"):
                continue
            with open(os.path.join(src_dir, fn), "r", encoding="utf-8") as f:
                record = json.load(f)
            out.write(json.dumps(_stringify(record)) + "\n")
            n += 1
    return n


def export(config):
    out_dir = config.get("output_dir", "outputs/hf_dataset")
    configs = config.get("configs", {
        "create": "benchmark_create", "fix": "benchmark_fix", "modify": "benchmark_modify"})
    data_root = os.path.join(os.getcwd(), "data")

    counts = {}  # {config_name: {split: count}}
    for name, dataset in configs.items():
        counts[name] = {}
        for split in ("train", "test"):
            src = os.path.join(data_root, dataset, split)
            dst_dir = os.path.join(out_dir, name)
            os.makedirs(dst_dir, exist_ok=True)
            n = _write_split(src, os.path.join(dst_dir, f"{split}.jsonl"))
            if n:
                counts[name][split] = n
                print(f"[{name}/{split}] wrote {n} rows")

    # provenance from a manifest (if present)
    provenance = {}
    for dataset in configs.values():
        man_path = os.path.join(data_root, dataset, "manifest.json")
        if os.path.exists(man_path):
            with open(man_path) as f:
                m = json.load(f)
            provenance = {"builder_model": m.get("builder_model"),
                          "validator_model": m.get("validator_model")}
            break

    card = _build_card(config, configs, counts, provenance)
    with open(os.path.join(out_dir, "README.md"), "w", encoding="utf-8") as f:
        f.write(card)
    print(f"Wrote dataset card + {sum(sum(c.values()) for c in counts.values())} rows to {out_dir}")


def _build_card(config, configs, counts, provenance):
    pretty = config.get("pretty_name", "Benchson JSON Benchmark")
    license_id = config.get("license", "mit")
    hf_repo = config.get("hf_repo", "<owner>/<repo>")
    code_repo = config.get("code_repo", "https://github.com/<owner>/benchson")

    # configs front-matter
    fm = ["---", f"pretty_name: {pretty}", f"license: {license_id}",
          "task_categories:", "- text-generation",
          "tags:", "- json", "- json-schema", "- structured-output", "- code",
          "configs:"]
    for name in configs:
        fm.append(f"- config_name: {name}")
        fm.append("  data_files:")
        for split in ("train", "test"):
            if counts.get(name, {}).get(split):
                fm.append(f"  - split: {split}")
                fm.append(f"    path: {name}/{split}.jsonl")
    fm.append("---")

    rows = "\n".join(
        f"| `{name}` | {counts.get(name, {}).get('train', 0)} | {counts.get(name, {}).get('test', 0)} |"
        for name in configs)
    today = datetime.datetime.now().date().isoformat()
    prov = ""
    if provenance:
        prov = (f"\nGround truth was generated by **{provenance.get('builder_model')}** "
                f"and round-trip verified by **{provenance.get('validator_model')}**.\n")

    body = f"""
# {pretty}

A content-grounded benchmark for JSON generation. Each instance is grounded in a
concrete object and carries a ground truth, so outputs are scored for correctness —
not merely schema-validity. Three task families (one config each):

- **create** — given a schema and a description, produce the matching JSON.
- **fix** — given a schema-violating object, repair it.
- **modify** — given an object and a free-text instruction, return the modified JSON.

Each is scored on three axes: **json_validity**, **schema_compliance**, and
**semantic_fidelity** (field values vs. the ground truth).

## Splits

`train` and `test` are drawn from **disjoint schema pools** — a model fine-tuned on
`train` is never evaluated on a schema it saw. Only `test` should be used for
scoring.

| config | train | test |
|---|---|---|
{rows}

## Usage

```python
from datasets import load_dataset
import json

ds = load_dataset("{hf_repo}", "create", split="test")
row = ds[0]
schema = json.loads(row["schema"])            # JSON fields are stored as strings
reference = json.loads(row["reference_json"])
```

Pin a frozen version with `revision=` (a git tag/branch/commit on the dataset repo):

```python
load_dataset("{hf_repo}", "create", revision="v1.0")
```

## Evaluation

Score a model on the held-out `test` split with the three metrics above. The Benchson
repo ([{code_repo}]({code_repo})) ships a ready-made scorer; two ways to use it.

### Option A — lm-evaluation-harness

Run via [EleutherAI's lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness);
the Benchson repo ships the task definitions in `lm_eval_tasks/`.

```bash
pip install lm-eval jsonschema deepdiff
# Grab lm_eval_tasks/ from the repo, then in each benchson_*.yaml point at this dataset:
#   dataset_path: {hf_repo}
#   dataset_name: create        # or fix / modify
#   test_split: test            # (drop the local dataset_kwargs.data_files)
lm_eval --model hf --model_args pretrained=<your-model> \\
  --tasks benchson --include_path lm_eval_tasks --apply_chat_template
```

### Option B — standalone (no harness)

`lm_eval_tasks/utils.py` is a self-contained scorer (needs only `jsonschema` +
`deepdiff`) that builds the prompt and computes the three metrics directly on these
rows — it accepts both the string-encoded fields here and raw objects.

```python
from datasets import load_dataset
from utils import doc_to_text_create, process_results_create   # copied from lm_eval_tasks/utils.py

ds = load_dataset("{hf_repo}", "create", split="test")
def my_model(prompt: str) -> str: ...        # call your model; return its text output

results = []
for row in ds:
    out = my_model(doc_to_text_create(row))
    results.append(process_results_create(row, [out]))
# average each of json_validity / schema_compliance / semantic_fidelity across `results`
```

Swap `create` → `fix` / `modify` with the matching `doc_to_text_*` / `process_results_*`.

## Fields

JSON-valued fields are stored as **strings** (parse with `json.loads`):

- **create**: `schema`, `description`, `reference_json`, `name`, `source`, `subset`
- **fix**: `schema`, `erroneous_json`, `valid_json`, `description`, `name`, `source`, `subset`
- **modify**: `schema`, `data`, `instructions`, `ground_truth`, `modification`, `name`, `source`, `subset`

## Provenance & licensing
{prov}
Schemas come from JSONSchemaStore (MIT) and JSONSchemaBench
(`epfl-dlab/JSONSchemaBench`, MIT, arXiv:2501.10868); `source`/`subset` on each row
record the origin. Released {today}. This dataset is licensed {license_id.upper()}.
"""
    return "\n".join(fm) + "\n" + body


def main():
    parser = argparse.ArgumentParser(description="Export benchmark to a HuggingFace dataset layout.")
    parser.add_argument("--config", type=str, required=True, help="Path to export config JSON.")
    args = parser.parse_args()
    with open(args.config, "r", encoding="utf-8") as f:
        config = json.load(f)
    export(config)


if __name__ == "__main__":
    main()
